# Generated by Django 6.0.4 on 2026-06-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Любимая категория'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('admin', 'Администратор')], default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
